### ISSUE TITLE
OneSignal appId hardcoded in template

### ISSUE THREAD

**Issue by reneisrael** [jtbray/brilliant-resume#1]
Hi, testing your template today I found this in templates/partials/base.html.twig :

`<script>
  var OneSignal = window.OneSignal || [];
  OneSignal.push(function() {
    OneSignal.init({
      appId: "903d3d9b-668e-4e2c-9e99-3a547e6aa5a7",
    });
  });
</script>`

Can you fix this? 
Thank you in advance.

**Comment by jtbray** [comment]
I will push an update by tomorrow that will abstract the appId & wrap the entire OneSignal script in a conditional to make the integration optional.

Thanks, good catch!

**Comment by jtbray** [comment]
Just committed a fix, which should be picked up by GPM momentarily: https://github.com/jtbray/brilliant-resume/commit/83ba2d8eaf518f795b3c1e7084d69dd3f95d8c11

Let me know if you find anything else!

JTB
