### ISSUE TITLE
markdown isn't supported in resume fields

### ISSUE THREAD

**Issue by xinity** [jtbray/brilliant-resume#5]
hey there,

first of all, many thanks for this awesome theme, it's really wonderful kudos! :+1: 

I've tried to add in the 'experience' fields some markdown syntax, like headers, so on and so forth but it doesn't seem to be working.

whatever I've tried, it always ended up as a single text file bloc without any indentation, bullet points...

Have I missed something?

Cheers !

**Comment by jtbray** [comment]
I'm happy to provide anything that helps this community, as it has helped me on so many occasions!

The theme does utilize the Codemirror editor provided by Grav & specified here: https://learn.getgrav.org/forms/blueprints/fields-available#the-editor-field

Grav docs state the editor defaults to supporting GFM (github flavored markdown), but you are absolutely right! It is not properly outputting markdown contents. There are no filters in place in the template displaying the field so this must certainly be an issue with my implementation of the editor field in the blueprints.

My first thought is to add the additional parameters for "codemirror" to all the editor definitions in all blueprints. Hopefully that will straighten this out & if so, I will push a fix for this later this afternoon.

Thanks for catching this & letting me know! :raised_hands:

Cheers!

**Comment by xinity** [comment]
awesome !!

let me know so I can test right away :)
by the way, I've found several other "bugs"/"limitations"

so i may open other issues in a very near future :)

**Comment by jtbray** [comment]
After some testing, it's precisely because I didn't use any filters in the templates that markdown is not being displayed!

I will need to update the editor fields used in the template with the "|markdown" filter & everything will be good to go!

Please do open any other issues regarding bugs/limitations/feature requests! This is what makes the open source community so valuable IMO!

**Comment by jtbray** [comment]
I've pushed an update that should fix this issue & it has been picked up by GPM.

Please go ahead an open up any other issues that you've come across! 😃

**Comment by xinity** [comment]
Hey there seems to be working! Awesome!! I've opened other issues as "promised"
